apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image: anastasiah8696/notes-app-ui:latest
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_HOST
              value: backend-service
          resources:
            # Define resource limits and requests as needed
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "256Mi"
              cpu: "250m"
