apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: database
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: DB_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: DB_PORT
              value: "27017"
          resources:
            # Define resource limits and requests as needed
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "500m"
