apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-app-ui
  template:
    metadata:
      labels:
        app: notes-app-ui
    spec:
      containers:
        - name: notes-app-frontend
          image: anastasiah8696/notes-app-ui:latest
          ports:
          imagePullPolicy: Never
	  restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app-backend
  template:
    metadata:
      labels:
        app: notes-app-backend
    spec:
      containers:
        - name: notes-app-backend
          image: anastasiah8696/notes-app-backend:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: IfNotPresent
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app-database
  template:
    metadata:
      labels:
        app: notes-app-database
    spec:
      containers:
        - name: notes-app-database
          image: mongo
          ports:
            - containerPort: 27017
          imagePullPolicy: IfNotPresent
