apiVersion: v1
kind: Service
metadata:
  name: notes-app-ui-service
spec:
  selector:
    app: notes-app-ui
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app-backend-service
spec:
  selector:
    app: notes-app-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app-database-service
spec:
  selector:
    app: notes-app-database
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
