apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: anastasiah8696/notes-app-backend:latest
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: database-service
            - name: DB_PORT
              value: "27017"
          resources:
            # Define resource limits and requests as needed
            limits:
              memory: "512Mi"
              cpu: "0.5"
            requests:
              memory: "256Mi"
              cpu: "250m"
